spring.application.name=ms-sp-gestionarchivos

spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://mascotas.vault.azure.net/
spring.cloud.azure.keyvault.secret.property-sources[0].enabled=true

spring.datasource.url=${SQLurl}
spring.datasource.username=${SQLuser}
spring.datasource.password=${SQLpassword}
spring.jpa.hibernate.ddl-auto=update

azure.blob.container-name=${container-name}
azure.blob.connection-string=${container-connection}